### ISSUE TITLE
109 commits behind master

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/esp32-wifi-manager#118]
Note that since August 2020, wifi-manager master hasn't been compatible with older than 4.2 ESP-IDFs. Maybe latest ESP-IDF and latest wifi-manager include updates that would help with the Wi-Fi issues we've had. Please review also wifi-manager updates because our fork seems to be behind a lot.

https://github.com/tonyp7/esp32-wifi-manager/commit/87e1f7b5fdf5a138794121ca2965badc4a64b30a#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by TheSomeMan** [comment]
our wifi-manager branch has been significantly rewritten, it is hardly possible to synchronize it with the original branch

**Comment by laurijamsa** [comment]
Okay, noted. But let's at least closely review the changes on the original projects and then decide if some of those would be important to be ported. Let's close this issue not before analysed and reported the outcome.

**Comment by ojousima** [comment]
The difference between the forks is pretty big, upstream branch builds on ESP SDK 4.2 while we're on 4.0.3 and aiming to update to 4.3 etc. It's a good idea to keep an eye on project, I've subscribed to notifications from there but I don't think we can cherry-pick some good changes here. 

I suggest closing this issue, chances are that importing some changes out of context would lead to new problems.
