### ISSUE TITLE
Optimize stack usage

### ISSUE THREAD

**Issue by TheSomeMan** [ruuvi/esp32-wifi-manager#239]
[link](https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/727)

**Comment by markoaamunkajo** [comment]
Check that gateway works ok with new stack limits
Test all functions

**Comment by markoaamunkajo** [comment]
Didn't spot anything out of the ordinary in logs.
Tried various configurations, updating firmware, MQTT setup etc.
